name = "ai-insights"
main = "resonator.cloudflare.logpush.js"
compatibility_date = "2026-01-01"
no_bundle = true
logpush = true

[observability]
enabled = true

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = false

[[r2_buckets]]
binding = "R2"
bucket_name = "resonator"

[ai]
binding = "AI"

[triggers]
crons = ["0 0 * * *"]