name = "resonator"
main = "resonator.cloudflare.js"
compatibility_date = "2026-01-01"
no_bundle = true

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
invocation_logs = false

[[r2_buckets]]
binding = "R2"
bucket_name = "resonator"

[ai]
binding = "AI"

[triggers]
crons = ["0 0 * * *"]
